name: yotufer
description: A command-line application for sync youtube channels
version: 0.1.0
author: markupcode <andrew.devels@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  app_interface:
    path: ./packages/app-interface

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
