name: app_domain

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  rxdart: any
  googleapis: any
  youtube_api:
    path: ../youtube-api
  youtube_profile:
    path: ../youtube-profile

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
